---
dist: xenial

language: python
python:
  - '3.6'
  - '3.7'

install:
  - pip3 install -r requirements.txt
  - pip3 install -r requirements-dev.txt
  - pip3 install mypy

script:
  - pytest
  - mypy degreepath/
  - flake8 degreepath/
