language: rust

rust:
  - stable
  - beta

cache: cargo

matrix:
  allow_failures:
    - rust: nightly
  fast_finish: true
  include:
    - name: nightly
      rust: nightly
      before_cache: |
        RUSTFLAGS="--cfg procmacro2_semver_exempt" cargo install cargo-tarpaulin -f

      after_success: |
        cargo tarpaulin --out Xml
        curl -s https://codecov.io/bash | bash
