[package]
name = "gobbldygook_area_auditor"
version = "0.1.0"
authors = ["Hawken Rives <hawkrives@fastmail.fm>"]
edition = "2018"

[dependencies]
serde = "1.0"
serde_derive = "1.0"
serde_yaml = "0.8"
void = "1.0"

[[bin]]
name = "gobbldygook-area-auditor"
path = "src/main.rs"
