[package]
name = "degreepath-auditor"
version = "0.1.0"
authors = ["Hawken Rives <hawkrives@fastmail.fm>"]
edition = "2018"

[dependencies]
indexmap = { version = "1.0", features = ["serde-1"] }
serde = { version = "1.0", features = ["derive"] }
void = "1.0"

# "binary" dependencies
serde_yaml = "0.8"
serde_json = "1.0"
