edition = "2018"
use_field_init_shorthand = true
use_try_shorthand = true
# format_doc_comments = true
# overflow_delimited_expr = true
# normalize_doc_attributes = true
# single_line_if_else = true
# single_line_if_else_max_width = 120
# use_small_heuristics = "Max"
max_width = 120
