[package]
name = "degreepath-parser"
version = "0.1.0"
authors = ["Hawken Rives <hawkrives@fastmail.fm>"]
edition = "2018"

[dependencies]
maplit = "1.0"
serde = "1.0"
serde_derive = "1.0"
void = "1.0"

[dev-dependencies]
serde_yaml = "0.8"
