[package]
name = "degreepath-parser"
version = "0.1.0"
authors = ["Hawken Rives <hawkrives@fastmail.fm>"]
edition = "2018"

[dependencies]
serde = "1.0"
serde_derive = "1.0"
void = "1.0"
indexmap = {version = "1.0", features = ["serde-1"]}

[dev-dependencies]
serde_yaml = "0.8"
