[package]
name = "degreepath-parser"
version = "0.1.0"
authors = ["Hawken Rives <hawkrives@fastmail.fm>"]
edition = "2018"

[dependencies]
indexmap = {version = "1.0", features = ["serde-1"]}
serde = { version = "1.0", features = ["derive"] }
void = "1.0"

[dev-dependencies]
serde_yaml = "0.8"
