---
name: Docker

'on': [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1

      - name: Docker Login
        uses: Azure/docker-login@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}

      - name: Docker Build
        run: |
          REPO=hub.docker.com/degreepath/degreepath
          TAG="$(date +%s)"

          docker build . --file Dockerfile --tag "$REPO:$TAG"
          docker push "$REPO:$TAG"

          docker tag degreepath "$REPO:${{ github.ref }}"
          docker push "$REPO:${{ github.ref }}"
