---
name: Docker

'on': [push]

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      REPO: docker.io/degreepath/degreepath

    steps:
      - uses: actions/checkout@v1

      - name: Docker Login
        uses: Azure/docker-login@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}

      - name: Set tag
        run: |
          echo ::set-env name=TAG::"$(date +%s)"

      - name: Docker Build
        run: |
          docker build . --file Dockerfile --tag "$REPO:$TAG"

      - name: Docker Push
        run: |
          docker push "$REPO:$TAG"
